<a href="https://colab.research.google.com/github/EvgeniaKantor/DI-Bootcamp/blob/main/ExercisesXP_W6D1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [49]:
import numpy as np

In [52]:
#Exercise1 Create a 1D NumPy array containing numbers from 0 to 9.
array_1d = np.arange(10)
print(array_1d)

[0 1 2 3 4 5 6 7 8 9]


In [57]:
#Exercise2 Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integer.
list_data = [3.14, 2.17, 0, 1, 2]
array_ex2 = np.array(list_data).astype(int)
array_ex2

array([3, 2, 0, 1, 2])

In [58]:
#Exercise2 Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integer.
list_data = [3.14, 2.17, 0, 1, 2]
array_ex2 = np.array(list_data, dtype = int)
array_ex2

array([3, 2, 0, 1, 2])

In [62]:
#Exercise3 Create a 3x3 NumPy array with values ranging from 1 to 9.
array_ex3 = np.arange(1, 10)
reshaped_array_ex3 = array_ex3.reshape(3,3)
reshaped_array_ex3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
#Exercise3 Create a 3x3 NumPy array with values ranging from 1 to 9.
array_ex3 = np.arange(1,10).reshape(3,3)
array_ex3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
#Exercise4 Create a 2D NumPy array of shape (4, 5) filled with random numbers.
array_ex4 = np.random.rand(4, 5)
array_ex4

array([[0.67603745, 0.31464375, 0.24305273, 0.09816461, 0.97393877],
       [0.35087457, 0.53835716, 0.58660818, 0.35547982, 0.07486414],
       [0.87211842, 0.59909349, 0.43182905, 0.80235424, 0.55607392],
       [0.25513747, 0.96471714, 0.87773657, 0.63745812, 0.97676997]])

In [70]:
#Exercise5 Select the second row from a given 2D NumPy array.
array_ex5 = np.random.randint(0, 100, size=(4, 5))
array_ex5

array([[ 3, 52, 72, 67, 34],
       [16, 59, 69, 18, 56],
       [ 6, 57, 76, 82,  5],
       [21, 71, 41,  5, 23]])

In [72]:
print(array_ex5[1])

[16 59 69 18 56]


In [73]:
#Exercise6 Reverse the order of elements in a given 1D NumPy array (first element becomes last).
array_ex6 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
reversed_array = array_ex6[::-1]
reversed_array

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [74]:
#Exercise6 Reverse the order of elements in a given 1D NumPy array (first element becomes last).
array_ex6 = np.arange(10)
reversed_array = array_ex6[::-1]
reversed_array

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [75]:
#Exercise7 Create a 4x4 identity matrix using NumPy.
identity_matrix = np.identity(4)
identity_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [76]:
#Exercise7 Create a 4x4 identity matrix using NumPy.
identity_matrix = np.eye(4)
identity_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [79]:
#Exercise8 Find the sum and average of a given 1D array.
array_ex8 = np.arange(10)
print('The sum:', np.sum(array_ex8))
print('The average:', np.mean(array_ex8))

The sum: 45
The average: 4.5


In [81]:
#Exercise9 Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.
array_ex9 = np.arange(1, 21).reshape(4, 5)
array_ex9

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [84]:
#Exercise10 Extract all odd numbers from a given NumPy array.
array_ex10 = np.arange(1, 10)
odd_numbers = array_ex10[array_ex10 % 2 != 0]
odd_numbers

array([1, 3, 5, 7, 9])